name: Extract Release ZIP
on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download ZIP from release
        run: |
          curl -L -o release.zip https://github.com/Gusabary/hello-world/releases/download/cffex-api/Datafeed2.0.zip

      - name: Commit and push extracted files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add release.zip
          git commit -m "Add files from release ZIP"
          git push origin main
